# Generated by Django 2.2.4 on 2019-09-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=150, verbose_name='Должность'),
        ),
    ]
