# Generated by Django 2.2.15 on 2020-08-04 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0007_auto_20200513_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenizedAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unrestricted_value', models.CharField(max_length=250, verbose_name='Адрес одной строкой (полный, с индексом)')),
                ('postal_code', models.CharField(max_length=6, verbose_name='Индекс')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.CharField(max_length=50, verbose_name='Дом')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Answer')),
            ],
            options={
                'verbose_name': 'TokenizedAdress',
                'verbose_name_plural': 'TokenizedAdresss',
            },
        ),
    ]
