# Generated by Django 2.2.15 on 2020-08-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20200805_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenizedadress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Индекс'),
        ),
    ]
