# Generated by Django 2.2.15 on 2020-08-13 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20200513_0901'),
        ('info', '0004_auto_20200805_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenizedadress',
            name='response',
            field=models.ForeignKey(default=434, on_delete=django.db.models.deletion.CASCADE, to='lists.Response'),
        ),
    ]
