export default {
    // Filled checklists

    FETCH_FILLED_CHECKLISTS: "FETCH_FILLED_CHECKLISTS",
    CREATE_FILLED_CHECKLISTS: "CREATE_FILLED_CHECKLISTS",
    UPDATE_FILLED_CHECKLISTS: "UPDATE_FILLED_CHECKLISTS",
    REMOVE_FILLED_CHECKLISTS: "REMOVE_FILLED_CHECKLISTS",

    // Filled checklist
    FETCH_FILLED_CHECKLIST: "FETCH_FILLED_CHECKLIST",
}