export default {

    // Reports
    FETCH_REPORT: "FETCH_REPORT",
    CREATE_REPORT: "CREATE_REPORT",
    FETCH_REPORTS: "FETCH_REPORTS",
    REMOVE_REPORT: "REMOVE_REPORT",

    // Filled checklists
    FETCH_FILLED_CHECKLISTS: "FETCH_FILLED_CHECKLISTS",
    CREATE_FILLED_CHECKLISTS: "CREATE_FILLED_CHECKLISTS",
    UPDATE_FILLED_CHECKLISTS: "UPDATE_FILLED_CHECKLISTS",
    REMOVE_FILLED_CHECKLISTS: "REMOVE_FILLED_CHECKLISTS",

    // Filled checklist
    FETCH_FILLED_CHECKLIST: "FETCH_FILLED_CHECKLIST",

    // Checklist
    FETCH_CHECKLIST: "FETCH_CHECKLIST",
    SEND_CHECKLIST: "SEND_CHECKLIST",
    CHECKLIST_AUTOCOMPLETE_FIELD: "CHECKLIST_AUTOCOMPLETE_FIELD",

    // Checklists
    FETCH_CHECKLISTS: "FETCH_CHECKLISTS",

    // User
    PROFILE: "PROFILE",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT"
}