# Generated by Django 2.2.4 on 2019-08-30 03:51

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Name')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Display order')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='HistoricalResponse',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('datetime_create', models.DateTimeField(blank=True, editable=False, verbose_name='Время добавления')),
                ('datetime_update', models.DateTimeField(blank=True, editable=False, verbose_name='Время обновления')),
                ('_enabled', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время активизации')),
                ('_disabled', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время отключения')),
                ('_active', models.SmallIntegerField(blank=True, default=True, editable=False, null=True, verbose_name='Активен')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Creation date')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Update date')),
                ('interview_uuid', models.CharField(max_length=36, verbose_name='Interview unique identifier')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'История Изменений',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSurvey',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('datetime_create', models.DateTimeField(blank=True, editable=False, verbose_name='Время добавления')),
                ('datetime_update', models.DateTimeField(blank=True, editable=False, verbose_name='Время обновления')),
                ('_enabled', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время активизации')),
                ('_disabled', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время отключения')),
                ('_active', models.SmallIntegerField(blank=True, default=True, editable=False, null=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=400, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, editable=False, verbose_name='Users can see it and answer it')),
                ('need_logged_user', models.BooleanField(default=True, editable=False, verbose_name='Only authenticated users can see it and answer it')),
                ('display_by_question', models.BooleanField(default=False, editable=False, verbose_name='Display by question')),
                ('template', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Template')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'История Изменений',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.IntegerField(verbose_name='Номер')),
                ('required', models.BooleanField(verbose_name='Обязателен?')),
                ('type', models.CharField(choices=[('text', 'Многострочный текст'), ('short-text', 'Однострочный текст'), ('radio', 'Выбор одного варианта'), ('select', 'Выпадающий список вариантов'), ('select-multiple', 'Выбор нескольких вариантов'), ('select_image', 'Изображение'), ('integer', 'Целое')], default='text', max_length=200, verbose_name='Тип')),
                ('choices', models.TextField(blank=True, help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .", null=True, verbose_name='Варианты ответа')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('survey', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('datetime_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('_enabled', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время активизации')),
                ('_disabled', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время отключения')),
                ('_active', models.SmallIntegerField(blank=True, default=True, editable=False, null=True, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('interview_uuid', models.CharField(max_length=36, verbose_name='Interview unique identifier')),
            ],
            options={
                'verbose_name': 'Set of answers to surveys',
                'verbose_name_plural': 'Sets of answers to surveys',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('datetime_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('_enabled', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время активизации')),
                ('_disabled', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время отключения')),
                ('_active', models.SmallIntegerField(blank=True, default=True, editable=False, null=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=400, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, editable=False, verbose_name='Users can see it and answer it')),
                ('need_logged_user', models.BooleanField(default=True, editable=False, verbose_name='Only authenticated users can see it and answer it')),
                ('display_by_question', models.BooleanField(default=False, editable=False, verbose_name='Display by question')),
                ('template', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Template')),
            ],
            options={
                'verbose_name': 'чеклист',
                'verbose_name_plural': 'чеклисты',
            },
        ),
    ]
