# Generated by Django 2.2.4 on 2019-09-08 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Name')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Display order')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, editable=False, verbose_name='Users can see it and answer it')),
                ('need_logged_user', models.BooleanField(default=True, editable=False, verbose_name='Only authenticated users can see it and answer it')),
                ('display_by_question', models.BooleanField(default=False, editable=False, verbose_name='Display by question')),
                ('template', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Template')),
            ],
            options={
                'verbose_name': 'чеклист',
                'verbose_name_plural': 'чеклисты',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('interview_uuid', models.CharField(max_length=36, verbose_name='Interview unique identifier')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='lists.Survey', verbose_name='Survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ответ на чеклист',
                'verbose_name_plural': 'Ответы на чеклисты',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('date_from', models.DateTimeField(verbose_name='Начало отсчета')),
                ('date_to', models.DateTimeField(verbose_name='Конец отсчета')),
                ('checklists', models.ManyToManyField(to='lists.Survey', verbose_name='Чеклисты')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.IntegerField(verbose_name='Номер')),
                ('required', models.BooleanField(verbose_name='Обязателен?')),
                ('is_key', models.BooleanField(verbose_name='Ключевой?')),
                ('type', models.CharField(choices=[('textarea', 'Многострочный текст'), ('text', 'Однострочный текст'), ('radio', 'Выбор одного варианта'), ('select', 'Выпадающий список вариантов'), ('select-multiple', 'Выбор нескольких вариантов'), ('select-image', 'Изображение'), ('integer', 'Целое')], default='textarea', max_length=200, verbose_name='Тип')),
                ('choices', models.TextField(blank=True, help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .", null=True, verbose_name='Варианты ответа')),
                ('key_choices', models.TextField(blank=True, null=True, verbose_name='Варианты ответа для попадания в отчет')),
                ('category', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='lists.Category', verbose_name='Category')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lists.Survey', verbose_name='Survey')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('survey', 'order'),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='lists.Survey', verbose_name='Survey'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lists.Question', verbose_name='Вопрос')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lists.Response', verbose_name='Отчет')),
            ],
        ),
    ]
