# Generated by Django 2.2.4 on 2019-08-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20190830_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Многострочный текст'), ('short-text', 'Однострочный текст'), ('radio', 'Выбор одного варианта'), ('select', 'Выпадающий список вариантов'), ('select-multiple', 'Выбор нескольких вариантов'), ('select-image', 'Изображение'), ('integer', 'Целое')], default='text', max_length=200, verbose_name='Тип'),
        ),
    ]
