# Generated by Django 2.2.8 on 2019-12-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_remove_response_interview_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('textarea', 'Многострочный текст'), ('text', 'Однострочный текст'), ('radio', 'Выбор одного варианта'), ('select', 'Выпадающий список вариантов'), ('select-multiple', 'Выбор нескольких вариантов'), ('select-image', 'Изображение'), ('integer', 'Целое'), ('address-autocomplete', 'Адрес (с автодополнением)')], default='textarea', max_length=200, verbose_name='Тип'),
        ),
    ]
