# Generated by Django 2.2.4 on 2019-09-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20190831_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('date_from', models.DateTimeField(verbose_name='Начало отсчета')),
                ('date_to', models.DateTimeField(verbose_name='Конец отсчета')),
                ('checklists', models.ManyToManyField(to='lists.Survey', verbose_name='Чеклисты')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
