# Generated by Django 2.2.12 on 2020-04-27 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20191225_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Имя')),
                ('lat', models.FloatField(verbose_name='Lat')),
                ('lon', models.FloatField(verbose_name='Lon')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapnodes', to='lists.Answer', verbose_name='Ответ на вопрос')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapnodes', to='lists.Response', verbose_name='Ответ на чеклист')),
            ],
            options={
                'verbose_name': 'Точка карты',
                'verbose_name_plural': 'Точки карты',
            },
        ),
    ]
