# Generated by Django 2.2.4 on 2019-09-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalresponse',
            name='author_updated',
        ),
        migrations.RemoveField(
            model_name='historicalsurvey',
            name='author_updated',
        ),
        migrations.RemoveField(
            model_name='response',
            name='author_updated',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='author_updated',
        ),
    ]
