# Generated by Django 2.2.12 on 2020-05-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_mapnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('textarea', 'Многострочный текст'), ('text', 'Однострочный текст'), ('radio', 'Выбор одного варианта'), ('select', 'Выпадающий список вариантов'), ('select-multiple', 'Выбор нескольких вариантов'), ('select-image', 'Изображение'), ('integer', 'Целое'), ('address-autocomplete', 'Адрес (с автодополнением)'), ('address-autocomplete', 'Номер телефона')], default='textarea', max_length=200, verbose_name='Тип'),
        ),
    ]
