# Generated by Django 2.2.4 on 2019-09-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20190903_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalresponse',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalsurvey',
            name='author',
        ),
        migrations.RemoveField(
            model_name='response',
            name='author',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='author',
        ),
    ]
