# Generated by Django 2.2.4 on 2019-09-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20190903_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_key',
            field=models.BooleanField(default=False, verbose_name='Ключевой?'),
            preserve_default=False,
        ),
    ]
