# Generated by Django 2.2.4 on 2019-09-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_question_is_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='key_choices',
            field=models.TextField(blank=True, null=True, verbose_name='Варианты ответа для попадания в отчет'),
        ),
    ]
